Ensure that setTimeout doesn't throw error for firefox extensions
Whenever you do this kind of angular check for setTimeout, it ends
up causing problems in Firefox extensions:

TypeError: 'setTimeout' called on an object that does not implement interface Window

To avoid this you need to bind the setTimeout to the window