I imagine the intention in #1509 was to also retry when the `describeNode` error was encountered.  I assume the description `resolveNode` got changed to `describeNode` at some point in puppeteer history; in any case this solves the following error on my laptop:
ProtocolError: Protocol error (DOM.describeNode): Cannot find context with specified id

with test cross-origin-iframes.test.ts - should replace the existing DOM nodes on iframe navigation with `isAttachIframe`