Try to fix: error TS7053: Element implicitly has an 'any' type because expression of type 'capturedAssetStatuses' can't be used to index type '{ node: serializedNodeWithId; initialOffset: { left: number; top: number; }; }'.